In [ ]:
from flowstab.temporal_network import ContTempNetwork, ContTempInstNetwork

In [15]:
source_nodes=[0, 1, 1]
target_nodes=[1, 2, 3]
starting_times=[0, 1, 2]
ending_times=[2.5, 2.5, 2.5]
cont_net=ContTempNetwork(source_nodes=source_nodes, target_nodes=target_nodes, starting_times=starting_times, ending_times=ending_times)

In [21]:
A = cont_net.compute_static_adjacency_matrix(start_time=0, end_time=1.5)
A.todense()

matrix([[0. , 1.5, 0. , 0. ],
        [1.5, 0. , 0.5, 0. ],
        [0. , 0.5, 0. , 0. ],
        [0. , 0. , 0. , 0. ]])

In [22]:
A = cont_net.compute_static_adjacency_matrix()
A.todense()

matrix([[0. , 2.5, 0. , 0. ],
        [2.5, 0. , 1.5, 0.5],
        [0. , 1.5, 0. , 0. ],
        [0. , 0.5, 0. , 0. ]])

In [23]:
cont_net.node_array

array([0, 1, 2, 3])

In [24]:
cont_net.events_table

   source_nodes  target_nodes  starting_times  ending_times  durations
0             0             1               0           2.5        2.5
1             1             2               1           2.5        1.5
2             1             3               2           2.5        0.5

In [25]:
cont_net._compute_time_grid()

In [26]:
cont_net.time_grid

          is_start
times id
0.0   0       True
1.0   1       True
2.0   2       True
2.5   0      False
      1      False
      2      False