In [1]:
from flowstab.temporal_network import ContTempNetwork, ContTempInstNetwork

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\Yasaman\anaconda3\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "c:\Users\Yasaman\anaconda3\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "c:\Users\Yasaman\anaconda3\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
    await result
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\Yasaman\AppData\Local\Temp\ipykernel_49696\4197992522.py", line 1, in <module>
    from flowstab.temporal_network import ContTempNetwork, ContTempInstNetwork
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\flowstab\__init__.py", line 111, in <module>
    from .flow_stability import FlowStability
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\flowstab\flow_stability.py", line 57, in <module>
    from .temporal_network import (
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\flowstab\temporal_network.py", line 29, in <module>
    import pandas as pd
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\pandas\__init__.py", line 38, in <module>
    from pandas.compat import (
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\pandas\compat\__init__.py", line 29, in <module>
    from pandas.compat.pyarrow import (
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\pandas\compat\pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\Yasaman\anaconda3\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "c:\Users\Yasaman\anaconda3\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "c:\Users\Yasaman\anaconda3\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
    await result
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\Yasaman\AppData\Local\Temp\ipykernel_49696\4197992522.py", line 1, in <module>
    from flowstab.temporal_network import ContTempNetwork, ContTempInstNetwork
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\flowstab\__init__.py", line 111, in <module>
    from .flow_stability import FlowStability
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\flowstab\flow_stability.py", line 57, in <module>
    from .temporal_network import (
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\flowstab\temporal_network.py", line 29, in <module>
    import pandas as pd
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\pandas\__init__.py", line 61, in <module>
    from pandas.core.api import (
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\pandas\core\api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\pandas\core\dtypes\dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\Yasaman\anaconda3\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "c:\Users\Yasaman\anaconda3\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "c:\Users\Yasaman\anaconda3\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
    await result
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\Yasaman\AppData\Local\Temp\ipykernel_49696\4197992522.py", line 1, in <module>
    from flowstab.temporal_network import ContTempNetwork, ContTempInstNetwork
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\flowstab\__init__.py", line 111, in <module>
    from .flow_stability import FlowStability
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\flowstab\flow_stability.py", line 57, in <module>
    from .temporal_network import (
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\flowstab\temporal_network.py", line 29, in <module>
    import pandas as pd
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\pandas\__init__.py", line 61, in <module>
    from pandas.core.api import (
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 53, in <module>
    from pandas.core import (
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\pandas\core\ops\__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\pandas\core\ops\array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\pandas\core\computation\check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "c:\Users\Yasaman\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\numexpr\__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\Yasaman\anaconda3\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "c:\Users\Yasaman\anaconda3\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "c:\Users\Yasaman\anaconda3\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
    await result
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\Yasaman\AppData\Local\Temp\ipykernel_49696\4197992522.py", line 1, in <module>
    from flowstab.temporal_network import ContTempNetwork, ContTempInstNetwork
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\flowstab\__init__.py", line 111, in <module>
    from .flow_stability import FlowStability
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\flowstab\flow_stability.py", line 57, in <module>
    from .temporal_network import (
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\flowstab\temporal_network.py", line 29, in <module>
    import pandas as pd
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\pandas\__init__.py", line 61, in <module>
    from pandas.core.api import (
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 67, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py", line 61, in <module>
    from pandas.core import (
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\pandas\core\nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "c:\Users\Yasaman\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\Users\Yasaman\anaconda3\Lib\site-packages\bottleneck\__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

AttributeError: _ARRAY_API not found

Could not load sparse_dot_mkl. Will use scipy.sparse for matrix products.

In [2]:
source_nodes=[0, 1, 1]
target_nodes=[1, 2, 3]
starting_times=[0, 1, 2]
ending_times=[2.5, 2.5, 2.5]
cont_net=ContTempNetwork(source_nodes=source_nodes, target_nodes=target_nodes, starting_times=starting_times, ending_times=ending_times)

In [3]:
A = cont_net.compute_static_adjacency_matrix(start_time=0, end_time=1.5)
A.todense()

matrix([[0. , 1.5, 0. , 0. ],
        [1.5, 0. , 0.5, 0. ],
        [0. , 0.5, 0. , 0. ],
        [0. , 0. , 0. , 0. ]])

In [4]:
A = cont_net.compute_static_adjacency_matrix()
A.todense()

matrix([[0. , 2.5, 0. , 0. ],
        [2.5, 0. , 1.5, 0.5],
        [0. , 1.5, 0. , 0. ],
        [0. , 0.5, 0. , 0. ]])

In [5]:
cont_net.node_array

array([0, 1, 2, 3])

In [6]:
cont_net.events_table

   source_nodes  target_nodes  starting_times  ending_times  durations
0             0             1               0           2.5        2.5
1             1             2               1           2.5        1.5
2             1             3               2           2.5        0.5

In [7]:
cont_net._compute_time_grid()

In [8]:
cont_net.time_grid

          is_start
times id
0.0   0       True
1.0   1       True
2.0   2       True
2.5   0      False
      1      False
      2      False

In [9]:
import numpy as np

In [12]:
cont_net.times

Index([0.0, 1.0, 2.0, 2.5], dtype='float64', name='times')

In [11]:
int(np.where(cont_net.times == 0)[0])

TypeError: only 0-dimensional arrays can be converted to Python scalars

In [ ]:
cont_net._get_closest_time(t=1.5)

TypeError: only 0-dimensional arrays can be converted to Python scalars